### ISSUE TITLE
async functionality

### ISSUE THREAD

**Issue by trbck** [FuGangqiang/pyxqueue#1]
Any plans to change this to async functionality? By the way, your code looks **heavily** inspired from http://charlesleifer.com/blog/multi-process-task-queue-using-redis-streams/ - might want to add a note/ comment. 

Cheers

**Comment by FuGangqiang** [comment]
> Any plans to change this to async functionality?

I'm sorry there is no plan for async, but you can use it with gevent.

> By the way, your code looks heavily inspired from http://charlesleifer.com/blog/multi-process-task-queue-using-redis-streams/ - might want to add a note/ comment.

thanks for reminder.
