### ISSUE TITLE
Fetching issue with `xpending_range`

### ISSUE THREAD

**Issue by cnvsureshg** [FuGangqiang/pyxqueue#2]
I'm getting this issue while implement
How to resolve this issue unable to understand?

`(venv) xxxx@xxxxx:~/$ python3 app.py 
1 worker processes started.
Press Ctrl+C to exit.
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "venv/lib/python3.8/site-packages/pyxqueue.py", line 250, in run
    pending_resp = self.client.xpending_range(
TypeError: xpending_range() missing 2 required positional arguments: 'min' and 'max'
`

This is my code:

`client = redis.Redis()
queue = TaskQueue(client, stream_key='background-task')

@queue.task
def sleep(n):
    print(f'going to sleep for {n} seconds')
    time.sleep(n)
    print(f'woke up after {n} seconds')

if __name__ == "__main__":
    queue.run(1)
    app.run(host='0.0.0.0', port=PORT, threaded=True, load_dotenv=True, debug=DEBUG)
`

**Comment by cnvsuresh** [comment]
Can you take this up? This is very helpful for us

**Comment by FuGangqiang** [comment]
Sorry for late reply
v0.1.1 fix it

**Comment by Gowtham-2505** [comment]
But still, we're able to see the older version in pypi packages library. 
pyxqueue==0.0.15

And this issue is not yet resolved there. Can you check this as the priority?

**Comment by cnvsureshg** [comment]
But still, we're able to see the older version in pypi packages library.
pyxqueue==0.0.15

And this issue is not yet resolved there. Can you check this as the priority?

**Comment by FuGangqiang** [comment]
change your requirements.txt:
```
pyxqueue==0.1.1
```
